### PR TITLE
Convert try-catch blocks in tests to JUnit assertThrows

### LINKED ISSUE #36: Use assertThrows() instead of try-catch in tests
In the tests, there is a lot of places where an exception is expected to be thrown and instead of using JUnits assertThrows(), a try-catch block is used and then fail() is called if the expected exception is not thrown. For example:

Current:
```java
try {
  client.clearLocatorCache(creds, doesNotExist);
  fail("exception not thrown");
} catch (TableNotFoundException ex) {}
```

Proposed:
```java
assertThrows(TableNotFoundException.class, ()-> client.clearLocatorCache(creds, doesNotExist));
```

### PR DESCRIPTION
**Pull request by DomGarguilo**
Closes #36 

In a lot of places in the tests, there are try-catch statements that are used to ensure that an exception is thrown. In this PR I tried to find usages of that pattern and replace them with `assertThrows()` statements which have a few advantages.

### CODE REVIEW

File: src/test/java/org/apache/accumulo/proxy/its/SimpleProxyBase.java [hunk 1]
```diff
@@ -974,320 +975,232 @@ public void testNamespaceClassLoadLoginFailure() {
...
+        DebugIterator.class.getName(), Collections.emptyMap());
+
+    assertThrows(NamespaceNotFoundException.class,
+        () -> client.deleteNamespace(creds, doesNotExist));
+
+    assertThrows(NamespaceNotFoundException.class,
+        () -> client.renameNamespace(creds, doesNotExist, "abcdefg"));
+
+    assertThrows(NamespaceNotFoundException.class, () -> client.setNamespaceProperty(creds,
+        doesNotExist, "table.compaction.major.ratio", "4"));
```
Comment (ctubbsii) [inline src/test/java/org/apache/accumulo/proxy/its/SimpleProxyBase.java:1115]: Since a lot of these are checking for the same exception, I was thinking you could just loop over all these lambda's, something like:

```java
    Stream.<Executable>of(() -> client.deleteNamespace(creds, doesNotExist),
      () -> client.renameNamespace(creds, doesNotExist, "abcdefg"),
      ...

    .forEach(executable -> assertThrows(NamespaceNotFoundException.class, executable));
 ```

This removes a lot of boilerplate, since we're testing the same thing over and over again. This is great if everything is passing, but it might be hard to troubleshoot which one had a problem when there's a failure. That might be easier to troubleshoot by adding a loop counter to track which executable failed to throw the expected exception and broke out of the loop.

In any case, it's fine the way you have it now.

File: src/test/java/org/apache/accumulo/proxy/its/SimpleProxyBase.java [hunk 2]
```diff
@@ -1738,17 +1639,15 @@ public void userPermissions() throws Exception {
...
-    } catch (AccumuloSecurityException ex) {}
+    if (isKerberosEnabled()) {
+      // Switch back to the extra user
+      UserGroupInformation.loginUserFromKeytab(otherClient.getPrincipal(),
+          otherClient.getKeytab().getAbsolutePath());
+      client = userClient;
+    }
+    String scanner = client.createScanner(user, tableName, null);
+    assertThrows(AccumuloSecurityException.class, () -> client.nextK(scanner, 100),
+        "stooge should not read table test");
```
Comment (ctubbsii) [inline src/test/java/org/apache/accumulo/proxy/its/SimpleProxyBase.java:1650]: The block was removed, causing variable name collisions for some variables, like `scanner`. If you prefer to reuse the variable names instead of renaming them, you can put them inside an anonymous block (keep the block, but drop the `try` and `catch`), as in:

```java
    {
      String scanner = client.createScanner(user, tableName, null);
      assertThrows(AccumuloSecurityException.class, () -> client.nextK(scanner, 100),
          "stooge should not read table test");
    }
```

Or you can just use a different variable name, like you did. It's up to you. I just wanted to make sure you were aware. I sometimes use anonymous blocks to more strictly control the scope of commonly named temporary variables, so they don't get accidentally referenced later.

File: src/test/java/org/apache/accumulo/proxy/its/SimpleProxyBase.java (hunk 1 above)
Comment (DomGarguilo) [reply src/test/java/org/apache/accumulo/proxy/its/SimpleProxyBase.java:1115]: I was considering doing something like this. I'll take another look

Comment (DomGarguilo) [reply src/test/java/org/apache/accumulo/proxy/its/SimpleProxyBase.java:1054]: Made these changes to one of the tests in e2fb8c55e1537194de54fdf8c35bd647a5eda5f4. Working on the others now.

**Review by ctubbsii — APPROVED** [review]
My earlier review should have been an approval with comments. If you want to make the additional changes from the discussion, that's fine, too. Either way works for me, but feel free to merge with or without those changes, as far as my review is concerned.
